// SPDX-FileCopyrightText: 2026 Wisbendji Fimerlus <archledger236@gmail.com>
// SPDX-License-Identifier: GPL-2.0-or-later
// Generated by packages/color-schemes/export-kits.py from the Plasma Fusion colour
// schemes. Do not edit; run the generator and packages/color-schemes/tests/check-kits.py.
import 'package:flutter/material.dart';

const ColorScheme fusionDark = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFF2F6FDF),
  onPrimary: Color(0xFFFFFFFF),
  secondary: Color(0xFF8AB8FF),
  onSecondary: Color(0xFFFFFFFF),
  surface: Color(0xFF1B2031),
  onSurface: Color(0xFFE8EBF4),
  error: Color(0xFFFF8A8F),
  onError: Color(0xFFFFFFFF),
  outline: Color(0xFFA3ABC2),
);

const ColorScheme fusionLight = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF2F6FDF),
  onPrimary: Color(0xFFFFFFFF),
  secondary: Color(0xFF2359C4),
  onSecondary: Color(0xFFFFFFFF),
  surface: Color(0xFFFFFFFF),
  onSurface: Color(0xFF141827),
  error: Color(0xFFB3262E),
  onError: Color(0xFFFFFFFF),
  outline: Color(0xFF4D546A),
);
