// SPDX-FileCopyrightText: 2026 Wisbendji Fimerlus <archledger236@gmail.com>
// SPDX-License-Identifier: GPL-2.0-or-later
// Generated by packages/color-schemes/export-kits.py from the Plasma Fusion colour
// schemes. Do not edit; run the generator and packages/color-schemes/tests/check-kits.py.
#include <imgui.h>

// PlasmaFusionDark.colors: the accent is its Colors:Selection BackgroundNormal (#2f6fdf).
void ApplyFusionDark(ImGuiStyle &style)
{
    style.Colors[ImGuiCol_Text] = ImVec4(0.910f, 0.922f, 0.957f, 1.000f);
    style.Colors[ImGuiCol_TextDisabled] = ImVec4(0.639f, 0.671f, 0.761f, 1.000f);
    style.Colors[ImGuiCol_WindowBg] = ImVec4(0.106f, 0.125f, 0.192f, 1.000f);
    style.Colors[ImGuiCol_ChildBg] = ImVec4(0.122f, 0.145f, 0.251f, 1.000f);
    style.Colors[ImGuiCol_PopupBg] = ImVec4(0.094f, 0.110f, 0.169f, 1.000f);
    style.Colors[ImGuiCol_Border] = ImVec4(0.137f, 0.165f, 0.278f, 1.000f);
    style.Colors[ImGuiCol_FrameBg] = ImVec4(0.149f, 0.176f, 0.298f, 1.000f);
    style.Colors[ImGuiCol_FrameBgHovered] = ImVec4(0.357f, 0.616f, 1.000f, 1.000f);
    style.Colors[ImGuiCol_FrameBgActive] = ImVec4(0.541f, 0.722f, 1.000f, 1.000f);
    style.Colors[ImGuiCol_TitleBg] = ImVec4(0.094f, 0.110f, 0.169f, 1.000f);
    style.Colors[ImGuiCol_TitleBgActive] = ImVec4(0.106f, 0.125f, 0.192f, 1.000f);
    style.Colors[ImGuiCol_Button] = ImVec4(0.149f, 0.176f, 0.298f, 1.000f);
    style.Colors[ImGuiCol_ButtonHovered] = ImVec4(0.357f, 0.616f, 1.000f, 1.000f);
    style.Colors[ImGuiCol_ButtonActive] = ImVec4(0.541f, 0.722f, 1.000f, 1.000f);
    style.Colors[ImGuiCol_Header] = ImVec4(0.184f, 0.435f, 0.875f, 1.000f);
    style.Colors[ImGuiCol_HeaderHovered] = ImVec4(0.357f, 0.616f, 1.000f, 1.000f);
    style.Colors[ImGuiCol_HeaderActive] = ImVec4(0.541f, 0.722f, 1.000f, 1.000f);
    style.Colors[ImGuiCol_CheckMark] = ImVec4(0.184f, 0.435f, 0.875f, 1.000f);
    style.Colors[ImGuiCol_SliderGrab] = ImVec4(0.184f, 0.435f, 0.875f, 1.000f);
    style.Colors[ImGuiCol_SliderGrabHovered] = ImVec4(0.357f, 0.616f, 1.000f, 1.000f);
    style.Colors[ImGuiCol_SliderGrabActive] = ImVec4(0.541f, 0.722f, 1.000f, 1.000f);
    style.Colors[ImGuiCol_TextSelectedBg] = ImVec4(0.184f, 0.435f, 0.875f, 0.350f);
}

// PlasmaFusionLight.colors: the accent is its Colors:Selection BackgroundNormal (#2f6fdf).
void ApplyFusionLight(ImGuiStyle &style)
{
    style.Colors[ImGuiCol_Text] = ImVec4(0.078f, 0.094f, 0.153f, 1.000f);
    style.Colors[ImGuiCol_TextDisabled] = ImVec4(0.302f, 0.329f, 0.416f, 1.000f);
    style.Colors[ImGuiCol_WindowBg] = ImVec4(1.000f, 1.000f, 1.000f, 1.000f);
    style.Colors[ImGuiCol_ChildBg] = ImVec4(1.000f, 1.000f, 1.000f, 1.000f);
    style.Colors[ImGuiCol_PopupBg] = ImVec4(0.961f, 0.965f, 0.980f, 1.000f);
    style.Colors[ImGuiCol_Border] = ImVec4(0.961f, 0.965f, 0.980f, 1.000f);
    style.Colors[ImGuiCol_FrameBg] = ImVec4(0.933f, 0.941f, 0.961f, 1.000f);
    style.Colors[ImGuiCol_FrameBgHovered] = ImVec4(0.357f, 0.616f, 1.000f, 1.000f);
    style.Colors[ImGuiCol_FrameBgActive] = ImVec4(0.184f, 0.435f, 0.875f, 1.000f);
    style.Colors[ImGuiCol_TitleBg] = ImVec4(0.961f, 0.965f, 0.980f, 1.000f);
    style.Colors[ImGuiCol_TitleBgActive] = ImVec4(1.000f, 1.000f, 1.000f, 1.000f);
    style.Colors[ImGuiCol_Button] = ImVec4(0.933f, 0.941f, 0.961f, 1.000f);
    style.Colors[ImGuiCol_ButtonHovered] = ImVec4(0.357f, 0.616f, 1.000f, 1.000f);
    style.Colors[ImGuiCol_ButtonActive] = ImVec4(0.184f, 0.435f, 0.875f, 1.000f);
    style.Colors[ImGuiCol_Header] = ImVec4(0.184f, 0.435f, 0.875f, 1.000f);
    style.Colors[ImGuiCol_HeaderHovered] = ImVec4(0.357f, 0.616f, 1.000f, 1.000f);
    style.Colors[ImGuiCol_HeaderActive] = ImVec4(0.184f, 0.435f, 0.875f, 1.000f);
    style.Colors[ImGuiCol_CheckMark] = ImVec4(0.184f, 0.435f, 0.875f, 1.000f);
    style.Colors[ImGuiCol_SliderGrab] = ImVec4(0.184f, 0.435f, 0.875f, 1.000f);
    style.Colors[ImGuiCol_SliderGrabHovered] = ImVec4(0.357f, 0.616f, 1.000f, 1.000f);
    style.Colors[ImGuiCol_SliderGrabActive] = ImVec4(0.184f, 0.435f, 0.875f, 1.000f);
    style.Colors[ImGuiCol_TextSelectedBg] = ImVec4(0.184f, 0.435f, 0.875f, 0.350f);
}
